### ISSUE TITLE
KeyError encountered when using gpt-3.5-turbo-16k

### ISSUE THREAD

**Issue by michilu** [rcmdnk/chatgpt-prompt-wrapper#48]
I attempted to use the gpt-3.5-turbo-16k model as GPT-4 is not yet available. However, I encountered a KeyError when trying to access `self.model_max_tokens[self.model]`. It seems that `gpt-3.5-turbo-16k` is not included in the model_max_tokens dictionary. Could you please update the list to include this model?

Error Details:

```python
File "chatgpt_prompt_wrapper/chatgpt/chatgpt.py", line 118, in set_model
    self.tokens_limit = self.model_max_tokens[self.model] - 1
                        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'gpt-3.5-turbo-16k'
```

https://github.com/rcmdnk/chatgpt-prompt-wrapper/blob/41b2e8cc135a07b72e6627a33e4225a24aba56ea/src/chatgpt_prompt_wrapper/chatgpt/chatgpt.py#L88-L107

**Comment by rcmdnk** [comment]
Thanks for making the issue.

At [v0.0.13](https://github.com/rcmdnk/chatgpt-prompt-wrapper/releases/tag/v0.0.13),
gpt-4-0613, gpt-4-32k-0613, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k and gp-3.5-turbo-16k-0613 are added.

In addition, from v0.0.13, you can add new models by adding `model_max_tokens` and `prices` definitions to the configuration file:

```
[global.model_max_tokens]
"gpt-3.5-turbo-16k" = 16384

[global.prices]
"gpt-3.5-turbo-16k" = [0.003, 0.004]
```


See [README](https://github.com/rcmdnk/chatgpt-prompt-wrapper#configuration-file) for details.

But anyway, I'd appreciate it if you make an issue when you find the new model not listed in the default configuration.

**Comment by michilu** [comment]
That's great! Your quick response and continuous improvement of the system are greatly appreciated.

Now, it seems that version v0.0.13 has not been published to PyPI yet. https://pypi.org/project/chatgpt-prompt-wrapper/#history Due to this, I encountered an error when trying to install it using brew install.
